export const RS_UI_POST_TOOGLE_SITE_SETTINGS_SUBMENUES = 'RS_UI_POST_TOOGLE_SITE_SETTINGS_SUBMENUES';
export const RS_PROC_LOGIN_BY_LOCALSTORAGE = 'RS_PROC_LOGIN_BY_LOCALSTORAGE';
export const RS_DASH_TOGGLE_COMPONENT = 'RS_DASH_TOGGLE_COMPONENT';
export const RS_BOARD_TOGGLE_COMPONENT = 'RS_BOARD_TOGGLE_COMPONENT';

export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SET_COASTAL_ZONE = 'SET_COASTAL_ZONE';

export const RS_CHOOSE_BOARD_COMP = 'RS_CHOOSE_BOARD_COMP';

export const HISTORY_SCROLL = 'HISTORY_SCROLL';
