export const UI_STATE_BOARDVIEW_COMM = 'UI_STATE_BOARDVIEW_COMM';
export const UI_STATE_BOARDVIEW_FULLMAP = 'UI_STATE_BOARDVIEW_FULLMAP';
export const UI_STATE_BOARDVIEW_DEFAULT = 'UI_STATE_BOARDVIEW_DEFAULT';
